### ISSUE TITLE
Contribution?

### ISSUE THREAD

**Issue by SnowballSH** [Tearth/Inanis#1]
Hey Tearth! I was following your project Cosette a while ago, and I was wondering where you were after the last commit. Here you are!

Just wondering, will you be accepting possible contributions to this engine? I'm trying to implement something in evaluation stuff :)
I don't know how to contact you so I thought I'll open this "issue".

Thanks and thanks for the inspiration from your other projects to.

**Comment by Tearth** [comment]
Hello! Thank you for the support, while I really appreciate this, I think that at this point I'm further going to run this project only by myself - the engine is still pretty immature and lacks any documentation, so I'm not confident about allowing contributions now. Eventually, I want to open the project for it in the future when I will be sure enough that I want to do it.

**Comment by SnowballSH** [comment]
Alright, thanks! Looking forward to the future of this engine :) I'll experiment stuff on my fork until then I guess.
