### ISSUE TITLE
CLI Option to directly enter into UCI mode

### ISSUE THREAD

**Issue by aspen-otr** [Tearth/Inanis#3]
Would there be any chance of a flag like `--uci` or just `uci` being passed as a command line argument so that it directly enters the UCI mode? This would be useful to easily test UCI chess engines with the only difference between them being the executing commands.

In my mind, it would look something like `inanis --uci` or `inanis uci`, but really it'd be up to you if you want to implement this at all.

Cheers! Looking forward to the development of this :)

**Comment by Tearth** [comment]
Hi! That's a good idea, I think it could be also extended to every command (not just uci), so we can call things like perft directly from the command line. I will try to find a bit of time for implementation since it looks like a pretty important QoL change.

**Comment by Tearth** [comment]
It's not a part of the official UCI standard, but I will think if there is some relatively easy way to do it.

**Comment by Tearth** [comment]
I've just released version 1.2.1, please let me know if the new changes work as intended.
